# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "pat"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["steflewandowski"]
  s.date = "2012-08-31"
  s.description = "Allows you to find geo-position for a UK postcode, as well as which local authority and ward the postcode resides."
  s.email = "stef@stef.io"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/pat.rb",
    "pat.gemspec",
    "spec/pat_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/steflewandowski/pat"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.22"
  s.summary = "Ultra-simple UK postcode to geodata lookup"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_runtime_dependency(%q<weary>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<weary>, ['~> 1.0.1'])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<weary>, [">= 0"])
  end
end

